# Generated by Django 5.0.6 on 2024-06-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=200)),
                ("published_date", models.DateField()),
                ("isbn_number", models.CharField(max_length=13)),
                ("pages", models.IntegerField()),
                (
                    "cover",
                    models.ImageField(blank=True, null=True, upload_to="book_covers/"),
                ),
                ("language", models.CharField(max_length=50)),
                ("genre", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
